HW 1 done
rbespalov/Navigation pull request #19
Opened 2022-10-13 19:58 UTC by rbespalov

2022-10-15 15:42 UTC, Konskii requested changes
Задание выполнено, замечания поправлены. Замечания по коду советую исправить - такое частое использование force unwrap и cast не очень хорошо)

2022-10-15 15:42 UTC, Konskii commented on NetworkManager.swift
> +                print ("Error, statuse code is \((respose as! HTTPURLResponse).statusCode)")
force cast, заменить на проверку конструкцией guard и реализовать вывод ошибки(сетевой) в случае неуспешного каста

2022-10-15 15:42 UTC, Konskii commented on NetworkManager.swift
> +        let task = session.dataTask(with: URL(string: configuration.rawValue)!) { data, respose, error in
force unwrap, заменить на проверку на nil и обработку в случае провала

2022-10-15 15:42 UTC, Konskii commented on NetworkManager.swift
> +                print("\((respose as! HTTPURLResponse).allHeaderFields)")
force cast

2022-10-15 15:42 UTC, Konskii commented on NetworkManager.swift
> +                print("\((respose as! HTTPURLResponse).statusCode)")
force cast

2022-10-15 15:42 UTC, Konskii commented on NetworkManager.swift
> +                // error - The Internet connection appears to be offline.
для чего?

2022-10-15 15:42 UTC, Konskii commented on NetworkManager.swift
> +            catch {
catch  должен идти на той же строке где и закрывающая блок do скобка

2022-10-15 15:42 UTC, Konskii commented on Navigation/SceneDelegate.swift
> +        NetworkManager.request(for: appConfiguration!)
тут force cast уместен, согласен

2022-10-16 09:35 UTC, rbespalov commented on NetworkManager.swift
> +                // error - The Internet connection appears to be offline.
это часть задания

2022-10-16 11:04 UTC, merged